import typer
from rich.console import Console
from rich.panel import Panel
from clutch_cli.api import get_client

console = Console()


def insight():
    """Get your AI generated weekly insight."""
    with get_client() as client:
        try:
            console.print("[dim]Generating your weekly insight...[/dim]")

            response = client.get("/insights/weekly")
            if response.status_code != 200:
                console.print("[red]❌ Failed to fetch insight.[/red]")
                raise typer.Exit(1)

            data = response.json()

            if "message" in data:
                console.print(f"[yellow]{data['message']}[/yellow]")
                raise typer.Exit()

            stats = data["stats"]
            summary = data["ai_summary"]

            console.print(Panel(
                f"[bold green]🧠 Weekly Insight[/bold green]\n\n"
                f"{summary}\n\n"
                f"[dim]─────────────────────────────[/dim]\n"
                f"📅 Week of: {data['week_start']}\n"
                f"💻 Commits: {stats['total_commits']} "
                f"across {stats['active_days']} active days\n"
                f"🔀 Pull Requests: {stats['total_prs']}\n"
                f"🐛 Issues: {stats['total_issues']}\n"
                f"⭐ Best Day: {stats['best_day']}\n\n"
                f"[dim]Generated by {data['generated_by']}[/dim]",
                title="[bold]Clutch — AI Insight[/bold]",
                border_style="green",
            ))

        except Exception as e:
            console.print("[red]❌ Could not connect to Clutch API.[/red]")
            raise typer.Exit(1)